# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

builds:
  - binary: bdcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
    ignore:
      - goos: darwin
        goarch: '386'

archives:
  - format: tar.gz
    name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'bdcli_checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  draft: true
chocolateys:
  - name: betterdiscordcli
    owners: BetterDiscord
    title: BetterDiscord CLI
    authors: BetterDiscord
    project_url: https://betterdiscord.app/
    url_template: "https://github.com/BetterDiscord/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: https://betterdiscord.app/resources/branding/logo_solid.png
    copyright: 2023 BetterDiscord Limited
    license_url: https://github.com/BetterDiscord/cli/blob/main/LICENSE
    project_source_url: https://github.com/BetterDiscord/cli
    docs_url: https://github.com/BetterDiscord/cli/wiki
    bug_tracker_url: https://github.com/BetterDiscord/cli/issues
    tags: "betterdiscord cli"
    summary: A cross-platform CLI for managing BetterDiscord
    description: A cross-platform CLI for managing BetterDiscord
    release_notes: "https://github.com/BetterDiscord/cli/releases/tag/v{{ .Version }}"
    skip_publish: true
