# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

builds:
  - binary: bdcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
    ignore:
      - goos: darwin
        goarch: '386'

archives:
  - format: tar.gz
    name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'bdcli_checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  draft: true
