# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser v2 configuration
version: 2

# Before hook - runs before the build
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: bdcli
    binary: bdcli
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'bdcli_checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Others'
      order: 999

release:
  draft: true
  replace_existing_draft: true
  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: replace
  header: |
    ## BetterDiscord CLI {{ .Tag }}

    Install with npm: `npm install -g @betterdiscord/cli@{{ .Version }}`
  footer: |
    **Full Changelog**: https://github.com/BetterDiscord/cli/compare/{{ .PreviousTag }}...{{ .Tag }}

# NPM publishing via go-npm
nfpms:
  - id: packages
    package_name: betterdiscord-cli
    vendor: BetterDiscord
    homepage: https://betterdiscord.app/
    maintainer: BetterDiscord Team
    description: A cross-platform CLI for managing BetterDiscord
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/betterdiscord-cli/LICENSE

chocolateys:
  - name: betterdiscordcli
    owners: BetterDiscord
    title: BetterDiscord CLI
    authors: BetterDiscord
    project_url: https://betterdiscord.app/
    url_template: "https://github.com/BetterDiscord/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: https://betterdiscord.app/resources/branding/logo_solid.png
    copyright: 2025 BetterDiscord Limited
    license_url: https://github.com/BetterDiscord/cli/blob/main/LICENSE
    project_source_url: https://github.com/BetterDiscord/cli
    docs_url: https://github.com/BetterDiscord/cli/wiki
    bug_tracker_url: https://github.com/BetterDiscord/cli/issues
    tags: "betterdiscord cli discord"
    summary: A cross-platform CLI for managing BetterDiscord
    description: |
      A cross-platform CLI for managing BetterDiscord.
      Provides commands to install, uninstall, and manage BetterDiscord on your system.
    release_notes: "https://github.com/BetterDiscord/cli/releases/tag/v{{ .Version }}"
    skip_publish: true

# Git configuration
git:
  ignore_tags:
    - 'nightly'
